# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
  reinforcement learning: 3
  graph neural network: 3
  mobility: 1
  taxi: 1
  lyft: 1
  uber: 1
  didi: 1
# 通知の閾値
score_threshold: 4

# 1日に通知する最大件数(制限したくない場合は大きな数字を入れる)
max_result: 5
