# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        sound: 2
        audio: 2
        noisy label: 1
        rainforcement learning: 3
        transformer: 2
    
# 通知の閾値
score_threshold: 0
